name: Build/dev

on:
  push:
    branches:
      - "dev"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build/dev Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          draft: true
          prerelease: true
          
          title: "Dev Build - ${{ github.ref }}"

          body: |
            **Attention !**
            - Ceci est une version "dev"
            - Cette version n'est pas stable.
          release: always